model:
  arch: blip_enc_dec
  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth"
  image_size: 480

datasets:
  coco_vqa: # name of the dataset builder
    vis_processor: 
        train: 
          name: "blip_coco_vis_train"
          image_size: 480
        eval:
          name: "blip_coco_vis_eval"
          image_size: 480
    text_processor:
        train: 
          name: "blip_coco_text"
        eval: 
          name: "blip_coco_text"
  vg_vqa: # name of the dataset builder
    vis_processor: 
        train: 
          name: "blip_coco_vis_train"
          image_size: 480
        eval:
          name: "blip_coco_vis_eval"
          image_size: 480
    text_processor:
        train: 
          name: "blip_coco_text"
        eval: 
          name: "blip_coco_text"

run:
  # task: captioning
  task: vqa
  # optimizer
  init_lr: 1e-5
  min_lr: 0
  weight_decay: 0.05
  max_epoch: 5
  batch_size: 32
  num_workers: 4

  max_len: 20
  min_len: 5
  num_beams: 3

  seed: 42 
  output_dir: "output/VQA"

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["test"] 

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  