datasets:
  avsd_dialogue: # name of the dataset builder
    dataset_card: dataset_card/avsd_dialogue.md 
    data_type: features #extracted features of videos (I3D, VGGish) # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/home/data/avsd/train_set4DSTC7-AVSD.json
          storage: avsd/annotations/train.json 
        val:
          url: /export/home/data/avsd/valid_set4DSTC7-AVSD.json
          storage: avsd/annotations/val.json 
        test:
          url: /export/home/data/avsd/test_set4DSTC7-AVSD.json
          storage: avsd/annotations/test.json 
      features:
        storage: /export/home/data/avsd/features/ 
