datasets:
  msrvtt_qa: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/qa_train.json
          storage: msrvtt/annotations/qa_train.json
        val:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/qa_val.json
          storage: msrvtt/annotations/qa_val.json
        test:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/qa_test.json
          storage: msrvtt/annotations/qa_test.json
        ans2label:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/train_ans2label.json
          storage: msrvtt/annotations/qa_ans2label.json
      videos:
        storage: /export/share/dongxuli/data/msrvtt_qa/videos
