datasets:
  msrvtt_retrieval: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/retrieval_train.json
          storage: msrvtt/annotations/retrieval_train.json
        val:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/retrieval_val.json
          storage: msrvtt/annotations/retrieval_val.json
        test:
          url: /export/share/dongxuli/data/lavis/msrvtt/annotations/retrieval_test.json
          storage: msrvtt/annotations/retrieval_test.json
      videos:
        storage: /export/share/dongxuli/data/msrvtt_retrieval/videos
