datasets:
  conceptual_caption_3m:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - /export/share/dongxuli/data/lavis/conceptual_captions/annotation/cc3m.json
          storage:
              - conceptual_caption/annotations/cc3m.json
      images:
          storage: conceptual_caption/images
          # storage: /export/share/datasets/vision_language/cc3m_resize
