datasets:
  vg_vqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]
    
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train: 
          url: 
              # - https://storage.googleapis.com/sfr-vision-language-research/datasets/vg_qa.json
              - /export/share/dongxuli/data/lavis/vg/annotations/vg_qa.json
          storage:
              - vg/annotations/vg_qa.json
      images:
        train: 
          url: 
              - [
                https://cs.stanford.edu/people/rak248/VG_100K_2/images.zip, 
                https://cs.stanford.edu/people/rak248/VG_100K_2/images2.zip
                ] 
          storage: 
              - vg/images/