model:
  arch: blip_enc_dec

  vit_type: "large"
  vit_grad_ckpt: True
  vit_ckpt_layer: 5
  batch_size: 16
  init_lr: 2e-6

  image_size: 384

  # bert config
  med_config_path: "configs/models/med_config.json"

  # generation configs
  # max_length: 20  
  # min_length: 5
  # num_beams: 3
  prompt: "a picture of "