model:
  arch: albef_vqa

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/ALBEF/albef_vqav2_lavis.pt"
  init_decoder_as_encoder: False # set to False if initialized from finetuned weights

  use_distill: True
  momentum: 0.995
  alpha: 0.4

  # vit encoder
  vit_type: "base"
  vit_grad_ckpt: False
  vit_ckpt_layer: 0
  vit_layer_norm_epsilon: 1e-6

  image_size: 384

  # bert config
  med_config_path: "configs/models/med_config_albef.json"
