model:
  arch: albef_classification
  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/ALBEF/albef_snli_ve_lavis.pt"
  num_classes: 3

  use_distill: True
  momentum: 0.995
  alpha: 0.4

  # vit encoder
  vit_type: "base"
  vit_grad_ckpt: False
  vit_ckpt_layer: 0
  vit_layer_norm_epsilon: 1e-6

  image_size: 384

  # bert config
  med_config_path: "configs/models/med_config_albef.json"
