model:
  arch: albef_retrieval
  pretrained: "https://storage.googleapis.com/sfr-pcl-data-research/ALBEF/ALBEF.pth"

  # vit encoder
  vit_type: "base"
  image_size: 384
  vit_ckpt_layer: 0
  vit_drop_path_rate: 0
  vit_layer_norm_epsilon: 1e-6
  vit_grad_ckpt: False

  # bert config
  med_config_path: "lavis/configs/models/med_config_albef.json"

  embed_dim: 256
  momentum: 0.995
  alpha: 0.4
  temp: 0.07
  use_distill: True

  max_txt_len: 30