# model:
#   arch: blip_pretrain

#   # vit encoder
#   vit_type: "large"
#   vit_grad_ckpt: True
#   vit_ckpt_layer: 5

#   image_size: 224

#   # bert config
#   med_config_path: "lavis/configs/models/med_large_config.json"

#   # generation configs
#   prompt: "a picture of "