model:
  arch: blip_caption
  # pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP/blip_coco_caption_large.pth"
  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"

  vit_type: "large"
  vit_grad_ckpt: True
  vit_ckpt_layer: 5

  image_size: 384

  # bert config
  med_config_path: "configs/models/med_large_config.json"

  # generation configs
  prompt: "a picture of "
