datasets:
  laion2B_multi:

    data_type: images

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      storage: /export/laion/laion2B-multi/part-00000/{00000..01743}.tar
